CREATE TABLE ROUTE_POLICY(FAB VARCHAR(16), PRODUCT VARCHAR(64), MAIN_ROUTE VARCHAR(64), SUB_ROUTE VARCHAR(64), ENABLED CHAR(1));
CREATE TABLE ROUTE_CONDITION(FAB VARCHAR(16), PRODUCT VARCHAR(64), CONDITION_NAME VARCHAR(64), ACTIVE_YN CHAR(1));
CREATE TABLE RECIPE_MAPPING(FAB VARCHAR(16), PRODUCT VARCHAR(64), ROUTE VARCHAR(64), ACTIVE_YN CHAR(1));
CREATE TABLE LOT_QUEUE(LOT_ID VARCHAR(64), FAB VARCHAR(16), ROUTE VARCHAR(64), STATUS VARCHAR(16));
CREATE TABLE DISPATCH_AUDIT(LOT_ID VARCHAR(64), ACTION VARCHAR(16), ROUTE VARCHAR(64), REASON VARCHAR(128));
CREATE TABLE LOT_HOLD(LOT_ID VARCHAR(64), REASON VARCHAR(128));
CREATE TABLE EQUIPMENT(EQ_ID VARCHAR(64), STATE VARCHAR(16), MODE VARCHAR(32));
CREATE TABLE COMMAND_TOKEN(CORRELATION_ID VARCHAR(64), TOKEN VARCHAR(256));
CREATE TABLE COMMAND_AUDIT(TOKEN VARCHAR(256), COMMAND VARCHAR(128));
